//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAPPCORONA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IDCita { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
        public string Hora { get; set; }
        public int IDMedico { get; set; }
        public int IDPaciente { get; set; }
    
        public virtual Pacientes Paciente { get; set; }
    }
}
