//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAPPCORONA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Colaborador
    {
        public int IDColaborador { get; set; }
        public string Usuario { get; set; }

        public string Contraseña { get; set; }
        //[StringLength(10, MinimumLength = 3, ErrorMessage = "Nombre no puede ser más corto de 3 letras")]
        public string Nombre { get; set; }
       // [StringLength(10, MinimumLength = 3, ErrorMessage = "Apellido no puede ser más corto de 3 letras")]
        public string Apellido { get; set; }
        public string Cargo { get; set; }
        [Display(Name = "Tel Personal")]
        public string TelPersonal { get; set; }
        [Display(Name = "Tel Oficina")]
        public string TelOficina { get; set; }
        [Required]
        [EmailAddress]
        public string Correo { get; set; }
    }
}