//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAPPCORONA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico1
    {
        public int IDMedico { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Lunes { get; set; }
        public string Martes { get; set; }
        public string Miercoles { get; set; }
        public string Jueves { get; set; }
        public string Viernes { get; set; }
        public string Sabado { get; set; }
        public string Titulos { get; set; }
        public byte[] Img { get; set; }
        public int IDEspecialidad { get; set; }
        public string IDUser { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Especialidade Especialidade { get; set; }
    }
}
