//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAPPCORONA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Paciente
    {
        public int IDPaciente { get; set; }
        [Required]
        [EmailAddress]
        public string Correo { get; set; }
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Nombre no puede ser más corto de 3 letras")]
        public string Nombre { get; set; }
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Apellido no puede ser más corto de 3 letras")]
        public string Apellido { get; set; }
        [StringLength(10, MinimumLength =3, ErrorMessage ="Apellido no puede ser más corto de 3 letras" )]
        [Display(Name = "Segundo Apellido")]
        public string SegundoApellido { get; set; }
        public string Identidad { get; set; }
        public int Edad { get; set; }

        public string Genero { get; set; }

        [Display(Name = "Nacionalidad")]
        public int IDNacionalidad { get; set; }
        [Display(Name = "Ciudad")]
        public int Ciudad { get; set; }
        [Display(Name = "Residencia")]
        public int Residencia { get; set; }
        public virtual Ciudade Ciudade { get; set; }
        public virtual Nacionalidad Nacionalidad { get; set; }
        public virtual Residencia Residencia1 { get; set; }
    }
        }
        public enum Gender
        {
            M,
            F
        }   