//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAPPCORONA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ServiciosEnPromocion
    {
        public int IDServiciosPromocion { get; set; }
        [Display(Name = "Precio Final")]
        public double PrecioFinal { get; set; }

        [Display(Name = "Promocion")]
        public int IDPromocion { get; set; }
        [Display(Name = "Servicio")]
        public int IDServicio { get; set; }

        public virtual Promocione Promocione { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}