//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminAPPCORONA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IDUsers { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public int Cotizaciones { get; set; }
        public int Rol { get; set; }
        public int Estado { get; set; }
    }
}
