//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaboradore
    {
        public int IDColaborador { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cargo { get; set; }
        public int TelPersonal { get; set; }
        public Nullable<int> TelOficina { get; set; }
        public string IDUsuario { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
