//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Citas = new HashSet<Cita>();
            this.ExpedientePacientes = new HashSet<ExpedientePaciente>();
        }
    
        public int IDPaciente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Identidad { get; set; }
        public int Edad { get; set; }
        public string Genero { get; set; }
        public Nullable<int> IDNacionalidad { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public Nullable<int> Residencia { get; set; }
        public string IDUser { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Citas { get; set; }
        public virtual Ciudade Ciudade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedientePaciente> ExpedientePacientes { get; set; }
        public virtual Nacionalidad Nacionalidad { get; set; }
        public virtual Residencia Residencia1 { get; set; }
    }
}
