//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.ServiciosEnPromocions = new HashSet<ServiciosEnPromocion>();
        }
    
        public int IDServicio { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Recomendaciones { get; set; }
        public string Contraindicaciones { get; set; }
        public string Advertencias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciosEnPromocion> ServiciosEnPromocions { get; set; }
    }
}
